//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class CritterPossessable : Possessable
{
	protected OnPossessListener listener;

	public override void possess ()
	{
		base.possess ();
		if (listener != null)
		{
			listener.onPossess ();
		}
		exorcise ();
	}

	public void setOnPossessListener(OnPossessListener possessListener)
	{
		listener = possessListener;
	}
}

public interface OnPossessListener
{
	void onPossess();
}
