public enum MessageType
{
    AbilityStatusChanged,
	AbilityCoolDownMessage,
	AbilityPlaced,
    PlayerMovementTypeChanged,
    PlayerGrabbedNPCs,
    PlayerReleasedNPCs,
	TimerStatusChanged,
	LureRadiusEntered,
	PlayerCaughtInTrap,
	LureReleased,
	TrapEntered,
	TrapReleased,
    CameraZoomIn,
    CameraZoomOut,
	PauseChanged,
	NPCDestroyed,
	NPCAlertLevel
}
